#!/usr/bin/env bash
# spl-run -- Runs a compiled Spannerlog program
set -eu
cd target
# deepdive do all > /dev/null

# deepdive db init
# deepdive do process/init/app
# deepdive do process/init/relation/articles
# deepdive do data/articles

start=$(date +%s%N)
./run.sh # Run generated execution script
end=$(date +%s%N)
logging-with-ts "Elapsed running time:"
(bc <<< "scale = 20; ($end-$start)/1000000000") | logging-with-ts

cd ..
