#!/usr/bin/env bash
set -eu -o pipefail

if [[ ! -e app.spl || ! -e db.url ]]; then
    error "Not inside a Spannerlog application: app.splog and db.url should be all present in a parent directory"
fi

# delete old target directory and create a new one
rm -rf target
mkdir target
mkdir target/udf

schema=()
ln -s "../db.url" "target/db.url"
if [[ -d input ]]; then
	ln -s "../input" "target/input"
	(extract-input-schema.py input) > target/edb.schema.json
	schema+=(-edb target/edb.schema.json)
fi
if [[ -d udf ]]; then
	(compile-udf-dir.py udf target/udf) > target/udf.schema.json
	schema+=(-udf target/udf.schema.json)
fi

# compile spannerlog program
cmd="java -jar $SPL_HOME/spannerlog-1.0-SNAPSHOT.jar -program app.splog ${schema[*]:-}"
($cmd 2>&1>&3 | print-error) 3> target/splog.json

(compile-to-ddlog.py target/splog.json target/udf) > target/app.ddlog

cd target
chmod -R 777 .* 
deepdive compile
cd ..

