#!/usr/bin/env bash
set -eu -o pipefail

if [[ ! -e app.splog || ! -e db.url ]]; then
    error "Not inside a Spannerlog application: app.splog and db.url should be all present in a parent directory"
fi

# delete old target directory and create a new one
rm -rf target
mkdir target
mkdir target/udf

schema=()
ln -s "../db.url" "target/db.url"
if [[ -d edb ]]; then
	ln -s "../edb" "target/input"
	(extract-edb-schema.py edb) > target/edb.schema.json
	schema+=(-edb target/edb.schema.json)
fi
if [[ -d ief ]]; then
	(extract-ief-schema.py ief) > target/ief.schema.json
	schema+=(-ief target/ief.schema.json)
fi

# compile spannerlog program
cmd="java -jar $SPLOG_HOME/spannerlog-1.0-SNAPSHOT.jar -program app.splog ${schema[*]:-}"
($cmd 2>&1>&3 | print-error) 3> target/splog.json

(compile-to-ddlog.py target/splog.json) > target/app.ddlog
(compile-rgx.py target/splog.json) > target/rgx.sql

cd target
chmod -R 777 .* 
deepdive compile
deepdive db init
deepdive do process/init/app > /dev/null

# add procedural code to postgres
url=$(eval echo "$(cat db.url)")
db=${url##*/}
psql -d $db -c "CREATE EXTENSION plpythonu"
psql -d $db -f ../../installation/lib/ner.sql # Always?

# (create-sql-script target/splog.json) > target/script.sql

cd ..
