#!/usr/bin/env bash
set -eu

if [[ ! -e app.splog || ! -e db.url ]]; then
    error "Not inside a Spannerlog application: app.splog and db.url should be all present in a parent directory"
fi

# delete old target directory and create a new one
rm -rf target
mkdir target

schema=() 
ln -s "../db.url" "target/db.url"
if [[ -d input ]]; then
	ln -s "../input" "target/input"
	(extract-input-schema.py) > target/edb.schema.json
	schema+=(edb.schema.json)
fi
if [[ -d udf ]]; then
	(compile-udf-dir.py) > target/udf.schema.json
	schema+=(udf.schema.json)
fi

# compile spannerlog program
(java -jar $SPLOG_HOME/spannerlog-1.0-SNAPSHOT.jar -compile app.splog ${schema[*]}) > target/app.ddlog
# if [ $? -eq 0 ]; then
#    cd target
#    chmod -R 777 .* 
#    deepdive compile
#    cd ..
# fi
